export const sectionStyleSettings = [
    {
        type: "header",
        content: "Spacing",
    },
    {
        id: "padding_left",
        label: "Padding left (px)",
        type: "number",
        placeholder: "0",
        info: "Space left of the section",
        default: 20,
    },
    {
        id: "padding_right",
        label: "Padding right (px)",
        type: "number",
        placeholder: "0",
        info: "Space right of the section",
        default: 20,
    },
    {
        id: "padding_top",
        label: "Padding top (px)",
        type: "number",
        placeholder: "0",
        info: "Space above the section",
        default: 20,
    },
    {
        id: "padding_bottom",
        label: "Padding bottom (px)",
        type: "number",
        placeholder: "0",
        info: "Space below the section",
        default: 20,
    },
    {
        id: "row_margin_bottom",
        label: "Row bottom margin (px)",
        type: "number",
        placeholder: "0",
        info: "Space below each row",
        default: 20,
    },
    {
        type: "header",
        content: "Responsive",
    },
    {
        id: "max_width",
        label: "Max width (px)",
        type: "number",
        placeholder: "0",
        info: "Prevent from the section from being full width (inspect how the other sections of the theme behave). Leave empty for full width.",
        default: 1200,
    },
    {
        id: "media_breakpoint",
        label: "Mobile breakpoint (px)",
        type: "number",
        placeholder: "0",
        info: "The point in which rows become vertical as the screen width becomes smaller (inspect how the other sections of the theme behave)",
        default: 768,
    },
    {
        type: "header",
        content: "Colors",
    },
    {
        id: "text_color",
        label: "Text color",
        type: "color",
        info: "Main section text color",
        default: "#000000",
    },
    {
        id: "bg_color",
        label: "Background color",
        type: "color",
        info: "Main section background color",
    },
]
